apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-go
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-go
  template:
    metadata:
      labels:
        app: redis-go
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
