apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 9005
